steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/orders-ms',
    ]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/534838057044/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'