version: '3.8'

services:
  orders-db:
    image: postgres:16.2
    container_name: orders-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ordersdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  